/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        body: ['"Inter"', "system-ui", "sans-serif"],
      },
      colors: {
        background: "#f8fafc",
        surface: "#ffffff",
        "surface-dim": "#f1f5f9",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        outline: "#cbd5e1",
        "outline-variant": "#e2e8f0",
        primary: "#0f766e",
        "primary-dark": "#115e59",
        "primary-soft": "#ccfbf1",
        "on-primary": "#ffffff",
        "primary-container": "#0d9488",
        "on-primary-container": "#ccfbf1",
        "inverse-primary": "#5eead4",
        secondary: "#2563eb",
        "secondary-dark": "#1d4ed8",
        "secondary-soft": "#dbeafe",
        "on-secondary": "#ffffff",
        "secondary-container": "#3b82f6",
        "on-secondary-container": "#1e3a8a",
        tertiary: "#4f46e5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6366f1",
        "on-tertiary-container": "#e0e7ff",
        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        success: "#059669",
        "success-soft": "#d1fae5",
        warning: "#d97706",
        "warning-soft": "#fef3c7",
        "primary-fixed": "#ccfbf1",
        "primary-fixed-dim": "#5eead4",
        "on-primary-fixed": "#042f2e",
        "on-primary-fixed-variant": "#115e59",
        "secondary-fixed": "#dbeafe",
        "secondary-fixed-dim": "#93c5fd",
        "on-secondary-fixed": "#172554",
        "on-secondary-fixed-variant": "#1e40af",
        "tertiary-fixed": "#e0e7ff",
        "tertiary-fixed-dim": "#a5b4fc",
        "on-tertiary-fixed": "#1e1b4b",
        "on-tertiary-fixed-variant": "#3730a3",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(15, 23, 42, 0.05)",
        DEFAULT: "0 1px 3px 0 rgba(15, 23, 42, 0.08), 0 1px 2px -1px rgba(15, 23, 42, 0.06)",
        md: "0 4px 6px -1px rgba(15, 23, 42, 0.08), 0 2px 4px -2px rgba(15, 23, 42, 0.06)",
        lg: "0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.06)",
        xl: "0 20px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.06)",
        soft: "0 2px 12px 0 rgba(15, 118, 110, 0.08)",
      },
    },
  },
  plugins: [],
};
