/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        body: ['"Inter"', "system-ui", "sans-serif"],
      },
      colors: {
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#4059aa",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#444651",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        primary: "#00236f",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#90a8ff",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        secondary: "#855300",
        "on-secondary": "#ffffff",
        "secondary-container": "#fea619",
        "on-secondary-container": "#684000",
        "secondary-fixed": "#ffddb8",
        "on-secondary-fixed": "#2a1700",
        tertiary: "#00311f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#004a31",
        "on-tertiary-container": "#27c38a",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#002113",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        fab: "0 8px 16px rgba(0, 35, 111, 0.2)",
      },
    },
  },
  plugins: [],
};
